#!/usr/bin/python3

import os
from sys import argv

version = argv[1]


os.system( f'sudo update-alternatives --set php /usr/bin/php{version}' )
os.system( f'sudo update-alternatives --set phar /usr/bin/phar{version}' )
os.system( f'sudo update-alternatives --set phar.phar /usr/bin/phar.phar{version}' )
