<?php

use Stripe\Exception\CardException;
use Stripe\Exception\InvalidRequestException;
use \Stripe\StripeClient;

/*
 * @param string $email
 *
 * @return: Stripe\Account
 */
function stripeCreateConnectedAccount($email)
{
    $stripe = new StripeClient( config('services.stripe.secret') );

    $capabilities = [
        'card_payments' => ['requested' => true],
        'transfers'     => ['requested' => true],
    ];

    $options = [
        'type'    => 'custom',
        'country' => 'US',
        'email'   => $email,
        'capabilities' => $capabilities,
    ];

    $account = $stripe->accounts->create($options);

    info("[STRIPE CREATE CONNECTED ACCOUNT][EMAIL $email] account object: ".json_encode($account));
    return $account;
}

/*
 * @param string $account_id
 *
 * @return string

function stripeCreateAccountOnboardingLink($account_id)
{
    $stripe = new StripeClient( config('services.stripe.secret') );

    $options = [
        'account'     => $account_id,
        'refresh_url' => url('/cleaner/billing/banking-info-error'),
        'return_url'  => url('/cleaner/billing/banking-info-success'),
        'type'        => 'account_onboarding',
    ];

    $link = $stripe->accountLinks->create( $options );
    return $link->url;
}

 */
function stripeCreateAccountLink( $account_id, $type = "account_onboarding")
{
    $stripe = new StripeClient( config('services.stripe.secret') );

    $options = [
        'account'     => $account_id,
        'refresh_url' => url('/cleaner/billing/banking-info-error'),
        'return_url'  => url('/cleaner/billing/banking-info-success'),
        'type'        => $type,
    ];

    $link = $stripe->accountLinks->create( $options );
    return $link->url;
}



/*
 * @param string $account_id
 *
 * @return: Stripe\Account
 */
function stripeRetrieveAccount($account_id)
{
    $stripe  = new StripeClient( config('services.stripe.secret') );
    $account = $stripe->accounts->retrieve( $account_id );

    return $account;
}


/*
 * @param: string $account_id
 *
 * @param: array $accountDetails ( with keys: account_holder_name, account_number, routing_number )
 *
 */
function stripeCreateExternalAccount($account_id, $accountDetails)
{
    $stripe  = new StripeClient( config('services.stripe.secret') );

    $options = [
        "currency" => config('services.stripe.currency'),
        "country" => "us",
        "object" => "bank_account",
        "account_holder_name" => $accountDetails['account_holder_name'],
        "routing_number"      => $accountDetails['routing_number'],
        "account_number"      => $accountDetails['account_number']
    ];

    $externalAccount = $stripe->accounts->createExternalAccount($account_id, [ 'external_account' =>  $options]);

    /* TODO: exception handling is left */

    return $externalAccount;
}

/*
 * @param: array $card ( with keys: number, exp_month, exp_year, cvc )
 *
 */
function stripeGenerateCardToken($card)
{
    $stripe  = new StripeClient( config('services.stripe.secret') );

    $options = compact('card');

    try {

        $token = $stripe->tokens->create($options);
        return ['status' => true, 'token' => $token, 'token_string' => $token->id ];

    } catch(\Stripe\Exception\CardException $e) {

        return ['status' => false, 'error' => $e, 'error_string' => $e->getMessage() ];
    }

    return ['status' => false, 'error_string' => 'Unknown error occured'];
}

/*
 * @param: array $options ( options which are accepted by stripe )
 *
 * @return: Stripe\Customer
 *
 */
function stripeCreateCustomer($options)
{
    $stripe   = new StripeClient( config('services.stripe.secret') );

    try {
        $customer = $stripe->customers->create( $options );
        return [ 'status' => true, 'resposne' => $customer ];

    } catch ( CardException $e ) {
        return ['status' => false, 'error' => $e, 'error_string' => $e->getMessage() ];
    }

    return $customer;
}

/*
 * Update customer object in stripe
 *
 * @param: string $customer_id ( id of customer in stripe )
 *
 * @param: array $options ( with keys: accepted by stripe )
 *
 * @return: array
 */
function stripeUpdateCustomer($customer_id, $options)
{
    $stripe   = new StripeClient( config('services.stripe.secret') );

    try {
        $customer = $stripe->customers->update( $customer_id, $options );
        return [ 'status' => true, 'resposne' => $customer ];

    } catch ( CardException $e ) {
        return ['status' => false, 'error' => $e, 'error_string' => $e->getMessage() ];
    }

    return $customer;
}

/*
 * Update customer default source ( payment method ) in stripe
 *
 * @param: string $customer_id ( id of customer in stripe )
 *
 * @param: string $source ( source is a token generated by stripe for bank account or card )
 *
 * @return: array
 */
function stripeUpdateCustomerSource($customer_id, $source)
{
    $options = [
        'source' => $source,
    ];

    $response = stripeUpdateCustomer($customer_id, $options);
    return $response;
}

/*
 *
 * @param: string $name
 *
 * @param: string $email
 *
 * @param: string $source ( source is a token generated by stripe for bank account or card )
 *
 * @return: array
 */
function stripeCreateCustomerWithSource($name, $email, $source)
{
    $options  = compact('name', 'email', 'source');
    $customer = stripeCreateCustomer($options);
    return $customer;
}

/*
 * Create charge in stripe
 *
 * @param: array $options ( with keys: accepted by stripe )
 *
 * @return: array
 */
function stripeCharge( $options )
{
    $stripe = new StripeClient( config('services.stripe.secret') );

    try {
        $charge = $stripe->charges->create( $options );
        return ['status' => true, 'response' => $charge, 'charge_id' => $charge->id ];

    } catch ( CardException $e ) {
        return ['status' => false, 'error' => $e, 'error_string' => $e->getMessage() ];
    }

    return [ 'status' => false, 'error_string' => 'unknown error'];
}


/*
 * Deduct an amount to attached source ( payment method )
 * of stripe customer.
 *
 * @param: string $customer_id ( id of customer in stripe )
 *
 * @param: string|int $amount_in_cents
 *
 * @param: string description
 *
 * @return: array
 */
function stripeChargeCustomer($customer_id, $amount_in_cents, $description)
{
	$options = [
        'customer' => $customer_id,
        'amount'   => $amount_in_cents,
        'description' => $description,
        'currency'    => config('services.stripe.currency'),

	];

    $charge  = stripeCharge( $options );
    return $charge;
}

/*
 *
 * @param: array $options ( with keys: accepted by stripe )
 *
 * @return: array
 */
function stripeTransfer( $options )
{
    $stripe = new StripeClient( config('services.stripe.secret') );

    try {
        $transfer = $stripe->transfers->create( $options );
        return ['status' => true, 'response' => $transfer, 'transfer_id' => $transfer->id ];
    } catch (InvalidRequestException $e) {
        return ['status' => false, 'exception' => $e];
    }    
    
}

/*
 * Transfer amount to connected account from the organization account
 *
 * @param: string|int $amount_in_cents
 *
 * @param: string $account_id ( stripe's connected account id )
 *
 * @param: string $description
 *
 * @return: array
 */
function stripeTransferAmountToConnectedAccount($amount_in_cents, $account_id, $description)
{
    $options = [
        'currency'    => config('services.stripe.currency'),
        'amount'      => $amount_in_cents,
        'destination' => $account_id,
        'description' => $description,
    ];

    $transferResp = stripeTransfer($options);
    return $transferResp;
}


function stripeRefund( $options )
{
    $stripe = new StripeClient( config('services.stripe.secret') );

    $refund = $stripe->refunds->create( $options );
    return ['status' => true, 'response' => $refund, 'refund_id' => $refund->id ];
}
